# fly.toml app configuration file generated for fpl-data-platform-summer-sandbar-3583 on 2026-07-27T18:57:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fpl-ingestion'
primary_region = 'jnb'

[build]
  dockerfile = "Dockerfile"

[processes]
  web = "dagster-webserver -h 0.0.0.0 -p 8080 -m fpl_ingestion.definitions"
  daemon = "dagster-daemon run -m fpl_ingestion.definitions"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  processes = ["web"]
  size = "shared-cpu-1x"
  memory = "1gb"

[[vm]]
  processes = ["daemon"]
  size = "shared-cpu-1x"
  memory = "1gb"
