fpl:
  target: default
  outputs:
    default:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST', 'postgres') }}"
      port: "{{ env_var('DBT_DB_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_DB_USER', 'fpl') }}"
      password: "{{ env_var('DBT_DB_PASSWORD', 'fpl') }}"
      dbname: "{{ env_var('DBT_DATABASE', 'fpl') }}"
      schema: analytics
      threads: 4